plugins: 
  - jest
  - fp

env:
  browser: true
  es2021: true
  jest: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - "plugin:fp/recommended"
overrides: []
globals: {
       describe: readonly,
       test: readonly,
       expect: readonly
}
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: 
    no-console: 0
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
    import/extensions: 
      - error
      - ignorePackages
      - js: always